### ISSUE TITLE
Feature: Carousel

### ISSUE THREAD

**Issue by Victor-Park** [Victor-Park/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click through carousel of images on homepage.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A carousel containing 6 images will be changing to the next image every 3 seconds. User has the option to click on one of the dots to display the image out of order. When a dot is clicked, 3 second timer resets. When the 6th image is displayed, carousel resets and starts back at the first image. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-06-01 at 9 16 29 AM](https://user-images.githubusercontent.com/99834589/171451731-85014680-a47b-4597-92dc-18df4a96d57e.png)
![Screen Shot 2022-06-01 at 9 16 22 AM](https://user-images.githubusercontent.com/99834589/171451737-07b6ec4b-c9e6-4a8e-97a4-7a30c79d1ada.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Download all necessary images and store in folder
- [ ] Create carousel.jsx
- [ ] Build a carousel with slide, controls, and indicators

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
